### ISSUE TITLE
create payment

### ISSUE THREAD

**Issue by MohamedRmadan** [moyasar/moyasar-node#25]
any updates for adding a create payment function?

**Comment by xAltmime** [comment]
للأسف الدوكمنتيشن لديهم تعععععععبانننن جداََ جداََ فيه اشياء كثيره لم يوضحوها تجربة سيئة والله العظيم . 

مافي حتى 
Examples

**Comment by codingride** [comment]
I second this. The documentation is worthless. I'm still trying to find out what API should I call to make a payment or what URL to redirect the user to.

**Comment by codingride** [comment]
F.Y.I.
This is what you need to read first https://moyasar.com/docs/
This https://moyasar.com/docs/api/?javascript comes later

**Comment by procd92** [comment]
Creating a payment through the API is not allowed, you should use the payment form described here: https://moyasar.com/docs/payments/create-payment/mpf/

Also checkout the best practices section for more information on how to save the payment id before redirecting the user.

But, you can use the API to retrieve payments or refund them.

We are always striving to improve our services and documentation and we hope this cleared things out for you
